### ISSUE TITLE
failed to iniliaze pl/sql language server

### ISSUE THREAD

**Issue by ali-ahnaf** [EwanDubashinski/plsqllang-client#5]
The following error pops up `failed to iniliaze pl/sql language server`. I added the java path but doesn't seem to work

**Comment by EwanDubashinski** [comment]
Please provide your java version and OS.
Have you tried both `JAVA_HOME` environment variable and extension setting `plsqllint.javaHome`?

**Comment by EwanDubashinski** [comment]
Do you still have this problem or I can close the issue?
